timeout: 10800s
options:
  substitution_option: ALLOW_LOOSE
  # job builds a docker image for amd64
  machineType: N1_HIGHCPU_32
steps:
  - name: gcr.io/k8s-testimages/gcb-docker-gcloud:v20200824-5d057db
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - TAG=$_GIT_TAG
      - BASE_REF=$_PULL_BASE_REF
      - REGISTRY=us.gcr.io/replay-gaming
      # default cloudbuild has HOME=/builder/home and docker buildx is in /root/.docker/cli-plugins/docker-buildx
      # set the home to /root explicitly to if using docker buildx
      - HOME=/root
    args:
    - -c
    - |
      gcloud auth configure-docker \
      && make push
substitutions:
  _GIT_TAG: "1.0.0"
  _PULL_BASE_REF: "master"
